add additional check for mesh download and copy logic

diff --git a/AATE/meshes/GridPro/downloadMeshes b/AATE/meshes/GridPro/downloadMeshes
--- a/AATE/meshes/GridPro/downloadMeshes
+++ b/AATE/meshes/GridPro/downloadMeshes
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 # This script download the pre-generated GridPro meshes to your hard drive.
 # Usage: ./downloadMeshes [coarse|fine]
@@ -16,6 +17,12 @@ fi
 
 MESH_TYPE="$1"
 domain=https://s3.eu-west-1.amazonaws.com/dl.openfoam.org/ICengines/TCC-III
+
+# Check if the meshTimes_$MESH_TYPE file exists
+if [ ! -f "meshTimes_$MESH_TYPE" ]; then
+    echo "Error: meshTimes_$MESH_TYPE file not found."
+    exit 1
+fi
 
 times="$(cat meshTimes_$MESH_TYPE | xargs)"
 
diff --git a/AATE/runGridProCase b/AATE/runGridProCase
--- a/AATE/runGridProCase
+++ b/AATE/runGridProCase
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 # This script can be run as a job script in a computing cluster
 # Insert your job submission script here
@@ -35,17 +36,23 @@ fi
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
 
 # Clone case and prepare
-runApplication -o foamCloneCase -add 0.orig caseTemplate gridProCase_$MESH_TYPE
+runApplication -o -s $MESH_TYPE foamCloneCase -add 0.orig caseTemplate gridProCase_$MESH_TYPE
 cd gridProCase_$MESH_TYPE/
-
 cp -r ../meshes/GridPro/$MESH_TYPE/meshToMesh_* constant/
+cp -r ../meshes/GridPro/meshTimes_$MESH_TYPE constant/meshTimes
+
+# Check if each meshToMesh_x folder exists for each mesh mapping instance in meshTimes
+awk '{print $1}' constant/meshTimes | while read -r map; do
+    if [ ! -d "constant/meshToMesh_$map" ]; then
+        echo "Error: Folder meshToMesh_$map does not exist for mesh instance $map in meshTimes_$MESH_TYPE"
+        exit 1
+    fi
+done
+
 
 # Copy start time mesh and initial conditions
 cp -r constant/meshToMesh_0/polyMesh constant/
 cp -r 0.orig 0
-
-# Create meshTimes file
-ls -d constant/meshToMesh_* | sed 's/.*meshToMesh_//' | sort -n > constant/meshTimes
 
 # Set number of subdomains
 foamDictionary system/decomposeParDict -entry numberOfSubdomains -set $NSLOTS
